### ISSUE TITLE
Implement ability to extract and keep track of users ID

### ISSUE THREAD

**Issue by MarcDavid99** [xatkit-bot-platform/labs-ut-platform#12]
Related to [UC-1](https://github.com/xatkit-bot-platform/labs-ut-platform/wiki/Use-Cases#uc-1-reply-to-incoming-message)
Also see [Facebook document's sender id](https://developers.facebook.com/docs/messenger-platform/reference/webhook-events/messages)

**Comment by taidopurason** [comment]
This is already implemented in the messenger intent provider
