### ISSUE TITLE
Facebook Messenger Confused by Not Getting a Response?

### ISSUE THREAD

**Issue by Raud0** [xatkit-bot-platform/labs-ut-platform#42]
There are several odd behaviours that seem to be related to Facebook Messenger not getting a reply to it's Webhooks. I wonder how ngrok ties into this.
1. When the platform gets stuck or is stopped, Facebook Messenger keeps repeating its last message, waiting for a response. I know that Xatkit core handles receiving several messages in a row, but isn't there a way to reaffirm Facebook that its message has been received, so it can stop sending it? Sometimes this leads to having to reset the connection between ngrok and Facebook, which causes annoyance and costs time.
2. Replying to previously unanswered messages. It makes sense that it would. Still, we require more intentionality behind this. I doubt a bot should spam several answers to the user in a row from its previous life, randomly travelling through different states. Something tells me this isn't really avoidable though.

**Comment by taidopurason** [comment]
Did some code refactoring. Please add unit tests for the new functionality in MessengerIntentProvider
