### ISSUE TITLE
Bot is unable to respond to unreacts

### ISSUE THREAD

**Issue by Raud0** [xatkit-bot-platform/labs-ut-platform#47]
Unlike with reacting, the webhook events sent out by facebook upon unreacting from something, don't include the `reaction` or `emoji` fields, and no intents can be created from zero.

What is sent is the message id, so if the bot had memory, it could look up what the reaction was and sent to and what it was. Using this information it could create an intent from its negation.

Still, how should the platform proceed if the message has multiple reactions? We wouldn't know which one was removed.

**Comment by taidopurason** [comment]
Bot is now able to respond to unreacts
