### ISSUE TITLE
Make the platform configureable when it comes to which messages' reactions are being converted to intents

### ISSUE THREAD

**Issue by AndreasTeder** [xatkit-bot-platform/labs-ut-platform#48]
Make it so that the user can configure in the bot, whether it 
1.  wants to get intents from reactions
1.  wants to get intents from reactions to the last message
1.  wants to get intents from reactions to any message

**Comment by Raud0** [comment]
You can get intents and events from reactions.
When you reply with a message, you can access its `message_id` through the returned `Response` data structure.
The reaction webhook also gives you the `message_id`.
The developer can save the `message_id` for the desired messages to see reactions on into memory and check it themselves. Implementing this further would be overengineering.
